export const crowdfundingCategories = [
  "Charity and Nonprofits",
  "Medical and Health",
  "Education",
  "Technology and Innovation",
  "Art and Culture",
  "Small Business",
  "Environment and Sustainability",
  "Personal Finance",
  "Community Projects",
  "Animal Welfare",
  "Sports and Recreation",
  "Travel and Adventure",
  "Food and Beverage",
  "Fashion and Design",
  "Film and Video",
  "Publishing",
  "Gaming",
  "Home and Family",
  "Technology and Gadgets",
  "Social Causes",
];